version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Expondo o PHP backend na porta 8080
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Expondo o Vue frontend na porta 3000
    depends_on:
      - backend

  database:
    image: mysql:latest  # ou postgres, conforme seu banco de dados
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: seu_banco
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha
    volumes:
      - db_data:/var/lib/mysql  # Para persistência de dados

volumes:
  db_data:
